package com.ddd.backend.conversation.overlay;

public enum OverlayClearReason {
    REPLACED, EXPIRED, NAVIGATION, SNAPSHOT_CHANGED, USER_ACTION, RECONNECT,
    SECURE_INPUT, RISK_WARNING, FINAL_CONFIRMATION, SESSION_TERMINATED, TARGET_INVALID
}
